from backend.detection.rules import run_rule_engine
from backend.detection.url_features import extract_url_features
from backend.detection.message_features import extract_message_features
from backend.detection.classifier import predict_scam_probability
from backend.detection.fusion import fuse_scores, calculate_risk_breakdown
from backend.detection.evidence import generate_evidence_cards, generate_red_flags, generate_action_plan
from backend.detection.multilingual import get_localized_explanations, LANGUAGES
